### ISSUE TITLE
안녕하세요 에러 문의 드립니다. 

### ISSUE THREAD

**Issue by rlaalstn1504** [affjljoo3581/Job-Recommend-Competition#2]
이전의 에러는 해결했는데, 새로운 에러를 해결하지 못하고 있습니다. 

전처리 부분인 preprocess.sh 파일에서 transforemer_2_8_0 의 첫부분인 

python preprocessing/preprocess.py res/train/KNOW_2017.csv res/test/KNOW_2017_test.csv --data_type=2017 --use_simcse_embeddings

를 실행하면 

Traceback (most recent call last):
  File "preprocessing/preprocess.py", line 199, in <module>
    main(parser.parse_args())
  File "preprocessing/preprocess.py", line 93, in main
    simcse_embeddings = get_text_embeddings_from_simcse(
  File "C:\Users\rlaal\anaconda3\envs\transformers_2_8_0\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\python\Job-Recommend-Competition-main\preprocessing\text_embedding.py", line 28, in get_text_embeddings_from_simcse
    from data.dataloader import convert_to_tensor, example_model_setting
  File "D:\python\Job-Recommend-Competition-main\preprocessing\data\dataloader.py", line 11, in <module>
    from KoBERT.kobert.utils import get_tokenizer
ModuleNotFoundError: No module named 'KoBERT'
 
다음과 같은 에러가 뜹니다.  
Job-Recommend-Competition-main\preprocessing\data 이 경로에 KoBERT 폴더를 복사해서 넣어봐도 에러가 해결되지 않네요 
이 경우 어떻게 해결하는지 도움을 받을 수 있을까요?

**Comment by affjljoo3581** [comment]
[해당 문서](https://github.com/affjljoo3581/Job-Recommend-Competition/blob/main/REPRODUCTION.md#preprocessing-dataset)에서 KoSimCSE 및 KoBERT의 환경설정에 관한 내용을 포함하고 있습니다. KoBERT가 KoSimCSE 레포지토리 내에 생성되기 때문에, 위의 과정을 잘 따랐다면 KoBERT를 모듈로 인식할 겁니다.

**Comment by rlaalstn1504** [comment]
감사합니다. 해결했습니다!
